# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/916d7a1f-7d19-4354-823b-6606cd3a516e/X-Plane 12 Betas/Aircraft/ILIAS/P180_Avanti_II/plugins/avanti"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/916d7a1f-7d19-4354-823b-6606cd3a516e/X-Plane 12 Betas/Aircraft/ILIAS/P180_Avanti_II/plugins/avanti"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/916d7a1f-7d19-4354-823b-6606cd3a516e/X-Plane 12 Betas/Aircraft/ILIAS/P180_Avanti_II/plugins/avanti/CMakeFiles" "/mnt/916d7a1f-7d19-4354-823b-6606cd3a516e/X-Plane 12 Betas/Aircraft/ILIAS/P180_Avanti_II/plugins/avanti//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/916d7a1f-7d19-4354-823b-6606cd3a516e/X-Plane 12 Betas/Aircraft/ILIAS/P180_Avanti_II/plugins/avanti/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named avanti

# Build rule for target.
avanti: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 avanti
.PHONY : avanti

# fast build rule for target.
avanti/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/build
.PHONY : avanti/fast

ImgWindow/ImgFontAtlas.o: ImgWindow/ImgFontAtlas.cpp.o
.PHONY : ImgWindow/ImgFontAtlas.o

# target to build an object file
ImgWindow/ImgFontAtlas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/ImgWindow/ImgFontAtlas.cpp.o
.PHONY : ImgWindow/ImgFontAtlas.cpp.o

ImgWindow/ImgFontAtlas.i: ImgWindow/ImgFontAtlas.cpp.i
.PHONY : ImgWindow/ImgFontAtlas.i

# target to preprocess a source file
ImgWindow/ImgFontAtlas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/ImgWindow/ImgFontAtlas.cpp.i
.PHONY : ImgWindow/ImgFontAtlas.cpp.i

ImgWindow/ImgFontAtlas.s: ImgWindow/ImgFontAtlas.cpp.s
.PHONY : ImgWindow/ImgFontAtlas.s

# target to generate assembly for a file
ImgWindow/ImgFontAtlas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/ImgWindow/ImgFontAtlas.cpp.s
.PHONY : ImgWindow/ImgFontAtlas.cpp.s

ImgWindow/ImgWindow.o: ImgWindow/ImgWindow.cpp.o
.PHONY : ImgWindow/ImgWindow.o

# target to build an object file
ImgWindow/ImgWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/ImgWindow/ImgWindow.cpp.o
.PHONY : ImgWindow/ImgWindow.cpp.o

ImgWindow/ImgWindow.i: ImgWindow/ImgWindow.cpp.i
.PHONY : ImgWindow/ImgWindow.i

# target to preprocess a source file
ImgWindow/ImgWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/ImgWindow/ImgWindow.cpp.i
.PHONY : ImgWindow/ImgWindow.cpp.i

ImgWindow/ImgWindow.s: ImgWindow/ImgWindow.cpp.s
.PHONY : ImgWindow/ImgWindow.s

# target to generate assembly for a file
ImgWindow/ImgWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/ImgWindow/ImgWindow.cpp.s
.PHONY : ImgWindow/ImgWindow.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

imgui/misc/cpp/imgui_stdlib.o: imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : imgui/misc/cpp/imgui_stdlib.o

# target to build an object file
imgui/misc/cpp/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : imgui/misc/cpp/imgui_stdlib.cpp.o

imgui/misc/cpp/imgui_stdlib.i: imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : imgui/misc/cpp/imgui_stdlib.i

# target to preprocess a source file
imgui/misc/cpp/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : imgui/misc/cpp/imgui_stdlib.cpp.i

imgui/misc/cpp/imgui_stdlib.s: imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : imgui/misc/cpp/imgui_stdlib.s

# target to generate assembly for a file
imgui/misc/cpp/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : imgui/misc/cpp/imgui_stdlib.cpp.s

src/gui.o: src/gui.cpp.o
.PHONY : src/gui.o

# target to build an object file
src/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/gui.cpp.o
.PHONY : src/gui.cpp.o

src/gui.i: src/gui.cpp.i
.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s
.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/main.c.s
.PHONY : src/main.c.s

src/menu.o: src/menu.c.o
.PHONY : src/menu.o

# target to build an object file
src/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/menu.c.o
.PHONY : src/menu.c.o

src/menu.i: src/menu.c.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/menu.c.i
.PHONY : src/menu.c.i

src/menu.s: src/menu.c.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/avanti.dir/build.make CMakeFiles/avanti.dir/src/menu.c.s
.PHONY : src/menu.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... avanti"
	@echo "... ImgWindow/ImgFontAtlas.o"
	@echo "... ImgWindow/ImgFontAtlas.i"
	@echo "... ImgWindow/ImgFontAtlas.s"
	@echo "... ImgWindow/ImgWindow.o"
	@echo "... ImgWindow/ImgWindow.i"
	@echo "... ImgWindow/ImgWindow.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... imgui/misc/cpp/imgui_stdlib.o"
	@echo "... imgui/misc/cpp/imgui_stdlib.i"
	@echo "... imgui/misc/cpp/imgui_stdlib.s"
	@echo "... src/gui.o"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

